print("Entrez les coordonnées du point A:")
print("xA:")
xA=int(input())
print("yA:")
yA=int(input())
print("Entrez les coordonnées du point B:")
print("xB:")
xB=int(input())
print("yB:")
yB=int(input())
print("Le milieu du segment AB est:a pour coordonnée:")
print("Xm=",(xA+xB)/2)
print("Ym=",(yA+yB)/2)