print("Entrez le nombre de jours:")
j=int(input())
print("Entrez le nombre d'heures :")
h=int(input())
print("Entrez le nombre de minutes:")
min=int(input())
print("Entrez le nombre de secondes:")
sec=int(input())
print(" Le nombre total de secondes est:" ,(j*60*60*24)+(h*60*60)+(min*60)+sec,"secondes")